### ISSUE TITLE
Lab3D修改config文件，这是把测试脚本改了吧？

### ISSUE THREAD

**Issue by ZauGinfai** [HeZephyr/MIT6.5840#23]
在Config.go里添加函数CondInstallSnapshot()，测试脚本是调用config.go的，生成的快照就没有不符合条件的，这应该有问题吧？

**Comment by HeZephyr** [comment]
其实没有问题的，上层应用需要参与到Raft的快照决策过程中，何时制作快照，何时应用快照。生成的快照确实都是符合条件的，但是放到applyCh后，peer的commitIndex可能推进了，所以从applyCh取出快照后还是需要判断是否过期，CondInstallSnapshot的逻辑是如果快照没过期，则更新raft的状态并保存快照。那config.go实际上就是上层应用，其中applierSnap则是上层应用中的applier协程。
